### ISSUE TITLE
Kollisjon

### ISSUE THREAD

**Issue by jsva** [inf112-v21/5H#47]
Brukerhistorie:
Som en spiller ønsker jeg at hvis en annen spiller står i veien for roboten min kan jeg skyve hans robot foran min (gitt at veien er klar), slik at jeg kan manipulere andre spilleres posisjon for min egen vinning.

ArbeidsOppgaver:
Lage en metode som sjekker om en annen robot står i veien for en robot som skal flyttes. Hvis det er tilfelle så skal den roboten returneres samt informasjon om den kan dyttes.

Akseptansekrav:
En metode som sjekker for kollisjon mellom en robot som flyttes og andre roboter. Må kunne plugges inn i Move-logikken på et senere tidspunkt

**Comment by spectraldesign** [comment]
Laget en funksjon som sjekker om en bevegelse vil forårsake kollisjon, og om den gjør det oppdaterer den objektet den kolliderer med. Ikke implementert skikkelig/testet enda, og dermed ikke pushet til master, da det avventer endringene i game klassen fra GUI endringer.
