### ISSUE TITLE
Scale textures

### ISSUE THREAD

**Issue by jsva** [inf112-v21/5H#52]
Skaler texture størrelsene ned slik at de ikke trenger å nedskaleres så mye av koden og forhåpentligvis improve performance.

F.eks. 500x500 --> 64x64

**Comment by spectraldesign** [comment]
64x64 blir for lite, testet og det får textures til å se pixelert ut, kan prøve med 128x128 eller 256x256

**Comment by spectraldesign** [comment]
500x500 var ikke problemet som skapte memory leak, så lukker denne da nedskalering av textures ikke lenger er en prioritet
