### ISSUE TITLE
Mer avansert brett / flere brett

### ISSUE THREAD

**Issue by jsva** [inf112-v21/5H#74]

**Comment by HakonHoie** [comment]
1:
Som spiller vil jeg ha et større utvalg av brett fordi jeg ønsker en progresjon i spillet
Akseptansekrav: Få flere brett slik at spillerene får et større utvalg
Arbeidsoppgave: Lag flere brett slik at spillerene får et større utvalg

2:
Som spiller ønsker jeg at det kommer nye utfordringer for hvert brett slik at spillet ikke blir for kjedelig og repeterende
Akseptansekrav: Hvert brett skal være unikt
Arbeidsoppgave: Tilpass hvert brett med de unike objektene
